### ISSUE TITLE
only standard icons are shown, instead the coded ones

### ISSUE THREAD

**Issue by kai452** [tessus/joplin-plugin-menu-shortcut-toolbar#1]
no fontawsame icons as coded in common.ts.
Joplin 2.2.7 and 2.3.3
Windows 7 -Desktop-App

**Comment by tessus** [comment]
Most plugins don't work with the WYSIWYG editor.

I'm running the latest dev version on macOS and the icons are displayed just fine.

**Comment by kai452** [comment]
Thanks for fast reply.
Oh I see: If I invoke the Code-Editor, the Icons are correctly shown.
Question is, why e.g. the note-statistic-plugin has its icon also in WYSIWYG editor.

I'll try to find out.

**Comment by kai452** [comment]
Hi again,

I was wrong with my example: note-statistic-plugin has its icon also not in WYSIWYG editor, there is no icon at all in any editor, only in note-view.

**Comment by tessus** [comment]
I have deactivated the actions in the WYSIWYG editor, because the actions are not compatible with it.

Unfortunately there's no way to show toolbar icons in the markdown editor and not show them in the WYSIWYG editor.
I hope this option will be added to Joplin core at one point. I don't know that part of the code, otherwise I'd implement it myself.

Can we close this issue?

**Comment by kai452** [comment]
Thanks again.
So let's take a closer look into the core...
